version: "2"
services:

  database:
    image: mysql
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knights

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: flask run --host 0.0.0.0 --reload --debugger
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - database
    links:
      - database:db
